import { ENUM_TOUR_CATEGORY, type ENUM_TOUR_CATEGORY_TYPE } from "../types";

export const TOUR_CATEGORY_LABELS: Record<ENUM_TOUR_CATEGORY_TYPE, string> = {
	[ENUM_TOUR_CATEGORY.CULTURAL_HISTORICAL]: "Cultural & Historical",
	[ENUM_TOUR_CATEGORY.RELIGIOUS_SPIRITUAL]: "Religious & Spiritual",
	[ENUM_TOUR_CATEGORY.ARCHAEOLOGICAL]: "Archaeological",
	[ENUM_TOUR_CATEGORY.ADVENTURE_OUTDOOR]: "Adventure & Outdoor",
	[ENUM_TOUR_CATEGORY.ECO_NATURE]: "Eco & Nature",
	[ENUM_TOUR_CATEGORY.HIKING_TREKKING]: "Hiking & Trekking",
	[ENUM_TOUR_CATEGORY.CITY_TOUR]: "City Tour",
	[ENUM_TOUR_CATEGORY.GASTRONOMY_CULINARY]: "Gastronomy & Culinary",
	[ENUM_TOUR_CATEGORY.PHOTOGRAPHY_CREATIVE]: "Photography & Creative",
	[ENUM_TOUR_CATEGORY.EDUCATIONAL]: "Educational",
	[ENUM_TOUR_CATEGORY.MASTER_CLASS_WORKSHOP]: "Master Class & Workshop",
	[ENUM_TOUR_CATEGORY.WELLNESS_SPA]: "Wellness & Spa",
	[ENUM_TOUR_CATEGORY.YOGA_MEDITATION]: "Yoga & Meditation",
	[ENUM_TOUR_CATEGORY.BUSINESS_MICE]: "Business & MICE",
	[ENUM_TOUR_CATEGORY.FAMILY_KIDS]: "Family & Kids",
	[ENUM_TOUR_CATEGORY.MULTI_DESTINATION]: "Multi Destination"
};
