import { createEnumMapper } from "@/shared/utils";

import {
	CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY,
	type TCatalogPreviewBackendTourCategory
} from "../types/catalog-preview-backend.types";
import {
	ENUM_CATALOG_PREVIEW_TOUR_CATEGORY,
	type ENUM_CATALOG_PREVIEW_TOUR_CATEGORY_TYPE
} from "../types/catalog-preview-tour-category.types";

const MAP_TOUR_CATEGORY: Partial<
	Record<
		ENUM_CATALOG_PREVIEW_TOUR_CATEGORY_TYPE,
		TCatalogPreviewBackendTourCategory
	>
> = {
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.ADVENTURE_OUTDOOR]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.AdventureOutdoor,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.ARCHAEOLOGICAL]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.Archaeological,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.BUSINESS_MICE]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.BusinessMice,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.CITY_TOUR]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.CityTour,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.CULTURAL_HISTORICAL]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.CulturalHistorical,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.ECO_NATURE]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.EcoNature,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.EDUCATIONAL]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.Educational,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.FAMILY_KIDS]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.FamilyKids,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.GASTRONOMY_CULINARY]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.GastronomyCulinary,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.HIKING_TREKKING]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.HikingTrekking,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.MASTER_CLASS_WORKSHOP]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.MasterClassWorkshop,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.MULTI_DESTINATION]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.MultiDestination,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.PHOTOGRAPHY_CREATIVE]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.PhotographyCreative,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.RELIGIOUS_SPIRITUAL]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.ReligiousSpiritual,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.WELLNESS_SPA]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.WellnessSpa,
	[ENUM_CATALOG_PREVIEW_TOUR_CATEGORY.YOGA_MEDITATION]:
		CATALOG_PREVIEW_BACKEND_TOUR_CATEGORY.YogaMeditation
};

export const catalogPreviewTourCategoriesMapper = createEnumMapper<
	ENUM_CATALOG_PREVIEW_TOUR_CATEGORY_TYPE,
	TCatalogPreviewBackendTourCategory
>(MAP_TOUR_CATEGORY);
