import { createEnumMapper } from "@/shared/utils";

import {
	ENUM_CATALOG_AMENITIES,
	type ENUM_CATALOG_AMENITIES_TYPE,
	ENUM_CATALOG_LANGUAGES,
	type ENUM_CATALOG_LANGUAGES_TYPE,
	ENUM_CATALOG_PICKUP_TYPE,
	type ENUM_CATALOG_PICKUP_TYPE_TYPE
} from "../types/catalog-labels.types";
import {
	CATALOG_PREVIEW_BACKEND_AMENITY,
	CATALOG_PREVIEW_BACKEND_LANGUAGE,
	CATALOG_PREVIEW_BACKEND_PICKUP_TYPE,
	type TCatalogPreviewBackendAmenity,
	type TCatalogPreviewBackendLanguage,
	type TCatalogPreviewBackendPickupType
} from "../types/catalog-preview-backend.types";

const MAP_LANGUAGES: Partial<
	Record<ENUM_CATALOG_LANGUAGES_TYPE, TCatalogPreviewBackendLanguage>
> = {
	[ENUM_CATALOG_LANGUAGES.RUSSIAN]: CATALOG_PREVIEW_BACKEND_LANGUAGE.Russian,
	[ENUM_CATALOG_LANGUAGES.ENGLISH]: CATALOG_PREVIEW_BACKEND_LANGUAGE.English,
	[ENUM_CATALOG_LANGUAGES.SPANISH]: CATALOG_PREVIEW_BACKEND_LANGUAGE.Spanish,
	[ENUM_CATALOG_LANGUAGES.ITALIAN]: CATALOG_PREVIEW_BACKEND_LANGUAGE.Italian,
	[ENUM_CATALOG_LANGUAGES.PORTUGUESE]:
		CATALOG_PREVIEW_BACKEND_LANGUAGE.Portuguese,
	[ENUM_CATALOG_LANGUAGES.UZBEK]: CATALOG_PREVIEW_BACKEND_LANGUAGE.Uzbek
};

export const catalogLanguageMapper = createEnumMapper<
	ENUM_CATALOG_LANGUAGES_TYPE,
	TCatalogPreviewBackendLanguage
>(MAP_LANGUAGES);

const MAP_AMENITIES: Partial<
	Record<ENUM_CATALOG_AMENITIES_TYPE, TCatalogPreviewBackendAmenity>
> = {
	[ENUM_CATALOG_AMENITIES.AIR_CONDITIONING]:
		CATALOG_PREVIEW_BACKEND_AMENITY.AirConditioning,
	[ENUM_CATALOG_AMENITIES.WIFI_ON_BOARD]:
		CATALOG_PREVIEW_BACKEND_AMENITY.Wifi,
	[ENUM_CATALOG_AMENITIES.BREAKFAST]:
		CATALOG_PREVIEW_BACKEND_AMENITY.Breakfast
};

export const catalogAmenitiesMapper = createEnumMapper<
	ENUM_CATALOG_AMENITIES_TYPE,
	TCatalogPreviewBackendAmenity
>(MAP_AMENITIES);

const MAP_PICKUP: Partial<
	Record<ENUM_CATALOG_PICKUP_TYPE_TYPE, TCatalogPreviewBackendPickupType>
> = {
	[ENUM_CATALOG_PICKUP_TYPE.AIRPORT]:
		CATALOG_PREVIEW_BACKEND_PICKUP_TYPE.AirportPickup,
	[ENUM_CATALOG_PICKUP_TYPE.HOTEL]:
		CATALOG_PREVIEW_BACKEND_PICKUP_TYPE.HotelPickup
};

export const catalogPickupMapper = createEnumMapper<
	ENUM_CATALOG_PICKUP_TYPE_TYPE,
	TCatalogPreviewBackendPickupType
>(MAP_PICKUP);
